DOUBLE="double"
TEXT="std::string"
g_GimGePowertransParaDic =
{

    [ "Sphere": [ [ "R", DOUBLE ] ] ],
    [ "RotationalEllipsoid": [ [ "LR", DOUBLE ],
    [ "WR", DOUBLE ],
    [ "H", DOUBLE ] ] ],
    [ "Cuboid": [ [ "L", DOUBLE ],
    [ "W", DOUBLE ],
    [ "H", DOUBLE ] ] ],
    [ "Table": [ [ "TL1", DOUBLE ],
    [ "TL2", DOUBLE ],
    [ "LL1", DOUBLE ],
    [ "LL2", DOUBLE ],
    [ "H", DOUBLE ] ] ],
    [ "OffsetRectangularTable": [ [ "T", DOUBLE ],
    [ "TW", DOUBLE ],
    [ "L", DOUBLE ],
    [ "LW", DOUBLE ],
    [ "H", DOUBLE ],
    [ "XOFF", DOUBLE ],
    [ "YOFF", DOUBLE ] ] ],
    [ "Cylinder": [ [ "R", DOUBLE ],
    [ "H", DOUBLE ] ] ],
    [ "BendingCylindrical": [ [ "R", DOUBLE ],
    [ "L", DOUBLE ],
    [ "Rad", DOUBLE ] ] ],
    [ "TruncatedCone": [ [ "TR", DOUBLE ],
    [ "BR", DOUBLE ],
    [ "H", DOUBLE ] ] ],
    [ "EccentricTruncatedCone": [ [ "TR", DOUBLE ],
    [ "BR", DOUBLE ],
    [ "H", DOUBLE ],
    [ "TOPXOFF", DOUBLE ],
    [ "TOPYOFF", DOUBLE ] ] ],
    [ "Ring": [ [ "DR", DOUBLE ],
    [ "R", DOUBLE ],
    [ "Rad", DOUBLE ] ] ],
    [ "RectangularRing": [ [ "DR", DOUBLE ],
    [ "R", DOUBLE ],
    [ "L", DOUBLE ],
    [ "W", DOUBLE ] ] ],
	[ "EllipticRing": [ [ "DR", DOUBLE ],
	[ "W", DOUBLE ],
	[ "L", DOUBLE ] ] ],
	[ "CircularGasket": [ [ "OR", DOUBLE ],
	[ "IR", DOUBLE ],
	[ "H", DOUBLE ],
	[ "Rad", DOUBLE ] ] ],
	[ "TableGasket": [ [ "TR", DOUBLE ],
	[ "OR", DOUBLE ],
	[ "IR", DOUBLE ],
	[ "H", DOUBLE ],
	[ "Rad", DOUBLE ] ] ],
	[ "SquareGasket": [ [ "L1", DOUBLE ],
	[ "W1", DOUBLE ],
	[ "L2", DOUBLE ],
	[ "W2", DOUBLE ],
	[ "H", DOUBLE ],
	[ "CT", INT ],
	[ "Rad", DOUBLE ],
	[ "C", DOUBLE ] ] ],
	[ "StretchedBody": [ [ "Array", TEXT ],
	[ "Normal", TEXT ],
	[ "L", DOUBLE ] ] ],
	[ "PorcelainBushing": [ [ "H", DOUBLE ],
	[ "R", DOUBLE ],
	[ "R1", DOUBLE ],
	[ "R2", DOUBLE ],
	[ "N", INT ] ] ],
	[ "ConePorcelainBushing": [ [ "H", DOUBLE ],
	[ "BR", DOUBLE ],
	[ "TR", DOUBLE ],
	[ "BR1", DOUBLE ],
	[ "BR2", DOUBLE ],
	[ "TR1", DOUBLE ],
	[ "TR2", DOUBLE ],
	[ "N", INT ] ] ],
	[ "Insulator": [ [ "N", INT ],
	[ "D", DOUBLE ],
	[ "N1", INT ],
	[ "H1", DOUBLE ],
	[ "R1", DOUBLE ],
	[ "R2", DOUBLE ],
	[ "R", DOUBLE ],
	[ "F", DOUBLE ],
	[ "A", DOUBLE ],
	[ "LN", INT ] ] ],
	[ "VTypeInsulator": [ [ "X", DOUBLE ],
	[ "AD", DOUBLE ],
	[ "N1", INT ],
	[ "H1", DOUBLE ],
	[ "R", DOUBLE ],
	[ "R1", DOUBLE ],
	[ "R2", DOUBLE ],
	[ "F", DOUBLE ],
	[ "A", DOUBLE ],
	[ "LN", INT ] ] ],
	[ "TerminalBlock": [ [ "L", DOUBLE ],
	[ "W", DOUBLE ],
	[ "T", DOUBLE ],
	[ "C", DOUBLE ],
	[ "CS", DOUBLE ],
	[ "RS", DOUBLE ],
	[ "R", DOUBLE ],
	[ "CN", INT ],
	[ "RN", INT ],
	[ "B", DOUBLE ],
	[ "Phase", TEXT ] ] ],
	[ "Rectangularfixedplate": [ [ "L", DOUBLE ],
	[ "W", DOUBLE ],
	[ "T", DOUBLE ],
	[ "CS", DOUBLE ],
	[ "RS", DOUBLE ],
	[ "CN", INT ],
	[ "RN", INT ],
	[ "MH", INT ],
	[ "D", DOUBLE ] ] ],
	[ "Circularfixedplate": [ [ "L", DOUBLE ],
	[ "W", DOUBLE ],
	[ "T", DOUBLE ],
	[ "CS", DOUBLE ],
	[ "N", INT ],
	[ "MH", INT ],
	[ "D", DOUBLE ] ] ],
	[ "Wire": [ [ "StartCoord", TEXT ],
	[ "EndCoord", TEXT ],
	[ "StartVector", TEXT ],
	[ "EndVector", TEXT ],
	[ "Sag", DOUBLE ],
	[ "D", DOUBLE ],
	[ "FitCoordArray", TEXT ] ] ],
	[ "Cable": [ [ "StartCoord", TEXT ],
	[ "EndCoord", TEXT ],
	[ "InflectionCoordArray", TEXT ],
	[ "IRArray", DOUBLE ],
	[ "D", DOUBLE ] ] ],
	[ "CableConcentration": [ [ "D", DOUBLE ],
	[ "Description", TEXT ],
	[ "Phase", TEXT ],
	[ "Center", TEXT ],
	[ "Direction", TEXT ]] ], 
	[ "CableSymbolicCurve",[["L", DOUBLE],
	[ "Category", TEXT ],
	[ "StartCoord", TEXT ],
	[ "Direction", TEXT ]] ], 
}